name: Python Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Cache VirtualEnv
      id: cache-venv
      uses: actions/cache@v1
      with:
        path: .venv
        key: ${{ runner.os }}-${{ hashFiles('*.txt') }}

    - uses: actions/checkout@v1
    - id: bento
      name: Bento
      uses: returntocorp/bento-action@v1
      with:
        acceptTermsWithEmail: gabriel@nacaolivre.org

    - name: Unit Tests
      run: make unit

    - name: Functional Tests
      run: make functional

    - name: Tests
      run: make tests

    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml # optional
